# Package Overview
package_name: fullstack_boosting_model

# Data Files
pipeline_name: boosting_pipe
pipeline_save_file: boosting
training_data_file: LandslideData.csv
test_data_file: test1.csv



modelchoice: boosting_dt

variables_to_rename:
  ID: ID
  aspect: ASPECT
  strdist: STREAM_DIST	
  basarea: BASE_AREA	
  basin: BASIN	
  curvature: CURVATURE	
  curve_cont: CURVE_CONT	
  curve_prof: CURVE_PROF	
  curves: CURVES	
  drop: DROP
  rockdist: ROCK_DIST	
  flowdir: FLOW_DIR	
  fos: FOS	
  lith: LITHOLOGY
  elev: ELEVATION
  cohesion: COHESION
  slide: LANDSLIDE
  scarpdist: SCARP_DIST
  scarps: SCARPS
  frictang: FRICTION_ANGLE
  slope: SLOPE
  slopeleg: SLOPE_LEG
  woods: WOODS
  specwt: SPECIFIC_WT

variables_to_reorder:
  ID: 0
  ASPECT: 1
  STREAM_DIST: 2
  BASE_AREA: 3	
  BASIN: 4
  CURVATURE: 5	
  CURVE_CONT: 6	
  CURVE_PROF: 7	
  CURVES: 8
  DROP: 9
  ROCK_DIST: 10	
  FLOW_DIR: 11
  FOS: 12
  LITHOLOGY: 13
  ELEVATION: 14
  COHESION: 15
  SCARP_DIST: 16
  SCARPS: 17
  FRICTION_ANGLE: 18
  SLOPE: 19
  SLOPE_LEG: 20
  WOODS: 21
  SPECIFIC_WT: 22
  LANDSLIDE: 23

numerical_vars_1:
  - ASPECT
  - BASE_AREA
  - BASIN
  - CURVATURE
  - CURVE_CONT
  - CURVE_PROF
  - CURVES
  - DROP
  - FLOW_DIR

numerical_vars_2:
  - FOS
  - ELEVATION
  - COHESION
  - FRICTION_ANGLE
  - SLOPE
  - SLOPE_LEG
  - SPECIFIC_WT

categorical_vars_1:
  - LANDSLIDE

categorical_vars_2:
  - LITHOLOGY
  - SCARPS
  - WOODS

astype_features:
  LANDSLIDE: 'int64'
  LITHOLOGY': 'int64'
  WOODS': 'int64'
  SCARPS': 'int64'

special_edit:
  - SCARPS

negative_variables:
  - CURVATURE
  - CURVE_CONT
  - CURVE_PROF

variables_to_drop:
  - ASPECT
  - LITHOLOGY

target: LANDSLIDE

features:
  - STREAM_DIST
  - BASE_AREA
  - BASIN
  - CURVATURE
  - CURVE_CONT
  - CURVE_PROF
  - CURVES
  - DROP
  - ROCK_DIST
  - FLOW_DIR
  - FOS
  - ELEVATION
  - COHESION
  - SCARP_DIST
  - SCARPS
  - FRICTION_ANGLE
  - SLOPE
  - SLOPE_LEG
  - WOODS
  - SPECIFIC_WT

# set train/test split
test_size: 0.1

# to set the random seed
random_state: 0

# The number of boosting stages to perform
n_estimators: 50

# loss function to be optimized
loss: ls

allowed_loss_functions:
  - ls
  - huber
